CREATE DATABASE SECOND;
USE SECOND;



CREATE TABLE INFORMATION (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    
    NAME VARCHAR (20),
	EMAIL VARCHAR (225) DEFAULT "XYZ@GMAIL.COM",
    DATE DATE DEFAULT CURRENT_TIMESTAMP,
    CONTACT VARCHAR (12) UNIQUE,
    ADDREES VARCHAR (225) DEFAULT "KARACHI",
    CINIC VARCHAR (15) UNIQUE, 
    IMEI VARCHAR (16) UNIQUE
);


SELECT * FROM INFORMATION;

INSERT INTO INFORMATION (NAME , EMAIL, CONTACT , CINIC ,IMEI) 
VALUES("ARSALAN","ARSALANAKBARALI53@GMAIL.COM" ,"03172479560" , "42101155782", "4837803495748344");