CREATE DATABASE LN3 ;
USE LN3;

CREATE TABLE LNO3(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    
    NAME VARCHAR (20),
    EMAIL VARCHAR (225) unique,
    AGE INT,
    SALARY INT,
    CONTACT_NUMBER INT (11) UNIQUE
    
    );
    
    SELECT * FROM LNO3;
    
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("M.ARSALAN","ARSALABARALI53@GMAIL.COM",17,25989,03172135467);
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("MUHAMMAD","XYX@GMAIL.COM",03,49048,03183648636);
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("MUNEERB","AAAA@GMAIL.COM",57,35637,03172249356);
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("ANAS","WNWO@GMAIL.COM",10,2909,031874785766);
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("ADBUL REHMAN","WW@GMAIL.COM",38,9868,03372649569);
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("SAAD","FF@GMAIL.COM",17,25989,03232646754);
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("ABU","DC@GMAIL.COM",77,9488,03172179569);
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("FATHER","VV@GMAIL.COM",57,84874,03172128738);
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("FAZOOL","DD@GMAIL.COM",37,93848,03564678367);
INSERT INTO LNO3 (NAME,EMAIL,AGE,SALARY,CONTACT) VALUES ("FAKLAK","GD@GMAIL.COM",27,983838,030857384);

ALTER TABLE LNO3 DROP COLUMN CONTACT_NUMBER;

ALTER TABLE LNO3 ADD CONTACT_NUMBER VARCHAR (225);

UPDATE LNO3 SET CONTACT_NUMBER='03172179569' WHERE ID='1';

ALTER TABLE LNO3 DROP COLUMN CONTACT_NUMBER;

ALTER TABLE LNO3 ADD COLUMN CONTACT VARCHAR (225) UNIQUE;

TRUNCATE TABLE LNO3;

-- Aggregate Fucntion

SELECT SUM(SALARY) FROM LNO3;
SELECT SUM(SALARY) AS 'SALARYS' FROM LNO3;

SELECT COUNT(NAME) FROM LNO3;
SELECT COUNT(NAME) AS 'NAMES' FROM LNO3;

SELECT AVG(SALARY) FROM LNO3;
SELECT AVG(SALARY) AS 'SALARY' FROM LNO3;

SELECT MIN(SALARY) FROM LNO3;
SELECT MIN(SALARY) AS 'SALARY' FROM LNO3;

SELECT MAX(SALARY) FROM LNO3;
SELECT MAX(SALARY) AS 'SALARY' FROM LNO3;

-- SCALAR FUNCTION

SELECT NAME , UPPER(NAME) FROM LNO3;
SELECT NAME , UPPER(NAME) AS 'NAMES' FROM LNO3;

SELECT NAME , LOWER(NAME) FROM LNO3;
SELECT NAME , LOWER(NAME) AS 'NAMES' FROM LNO3;

SELECT NAME , LENGTH(NAME) FROM LNO3;
SELECT NAME , LENGTH(NAME) AS 'NAMES' FROM LNO3;

SELECT NAME , SUBSTRING(NAME,3,2) FROM LNO3;
SELECT NAME , SUBSRTING(NAME,3,2) AS 'SHORTHAND' FROM LNO3;

SELECT SALARY , ROUND(SALARY,2) FROM LNO3;
SELECT SALARY , ROUND(SALARY,2) AS 'SALARY' FROM LNO3;

SELECT CURRENT_TIMESTAMP;

SELECT FORMAT(SALARY,2) FROM LNO3;
SELECT FORMAT(SALARY,2) AS 'SALARY' FROM LNO3;