CREATE DATABASE ARSALAN;
USE ARSALAN;


CREATE TABLE TEACHERS(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TEACHERS NVARCHAR(100),
    TEACHERSHAED NVARCHAR(225),
    SALARY INT DEFAULT 25000,
    GENDER NVARCHAR (225)
    
);

INSERT INTO TEACHERS values (1,"SYED MUHAMMAD ARSALAN SHAH",55000,"MALE", "MUHAMMAD ARSALAN");
INSERT INTO TEACHERS values (2,"MAHAK",10000,"FEMALE" ,"MUHAMMAD ARSALAN");
INSERT INTO TEACHERS values (3,"AYAN", 15000,"MALE","MUHAMMAD ARSALAN");
INSERT INTO TEACHERS values (4,"MUTEEBA",10000,"FEMALE","MUHAMMAD ARSALAN"); 

SELECT * 
		FROM
			TEACHERS;
CREATE TABLE STUDENTS(
		ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        NAME NVARCHAR (50),
        AGE INT ,
        GENDER NVARCHAR(225),
        TEACHERSID INT ,
        fOREIGN KEY (TEACHERSID)
			REFERENCES TEACHERS (ID)
);
SELECT * 
		FROM
			STUDENTS;
            
Insert into STUDENTS values (1, 'Ali',15, 'Male', 2);
Insert into STUDENTS values (2, 'Fatimah',20, 'Female'  , 4);
Insert into STUDENTS values (3, 'Muhammad',64, 'Male' , 1);
Insert into STUDENTS values (4,'Ayesha',26, 'Female' , 2);
Insert into STUDENTS values (null, 'Yusuf',24, 'Male' , 3);
Insert into STUDENTS values (null, 'Hassan',35, 'Male' , 1);
Insert into STUDENTS values (null, 'Maryam',18, 'Female' , 2);
Insert into STUDENTS values (null, 'Moosa',58, 'Male', 4);
Insert into STUDENTS values (null, 'Haroon',65, 'Male',  NULL);

-- INNER JOINS

SELECT 
		TEACHERS ,TEACHERSHAED, NAME
									FROM TEACHERS
												INNER JOIN 
															STUDENTS ON TEACHERS.ID = STUDENTS.TEACHERSID;

-- LEFT JOIN

SELECT 
		TEACHERS ,TEACHERSHAED, NAME
									FROM TEACHERS
												LEFT JOIN 
															STUDENTS ON TEACHERS.ID = STUDENTS.TEACHERSID;

-- RIGHT JOIN

SELECT 
		TEACHERS ,TEACHERSHAED, NAME
									FROM TEACHERS
												RIGHT JOIN 
															STUDENTS ON TEACHERS.ID = STUDENTS.TEACHERSID;
													
-- FULL JOIN

SELECT 
		TEACHERS ,TEACHERSHAED, NAME
									FROM TEACHERS
												LEFT JOIN 
															STUDENTS ON TEACHERS.ID = STUDENTS.TEACHERSID
UNION
SELECT 
		TEACHERS ,TEACHERSHAED, NAME
									FROM TEACHERS
												RIGHT JOIN 
															STUDENTS ON TEACHERS.ID = STUDENTS.TEACHERSID;
