CREATE DATABASE ARSALAN;

USE ARSALAN;

CREATE TABLE INFO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,

    NAME VARCHAR (225),
    EMAIL VARCHAR (225),
    CONTACT VARCHAR (225),
    AGE VARCHAR (225),
    DOB VARCHAR (225)
);

SELECT * FROM INFO;

INSERT into INFO (NAME, EMAIL,CONTACT,AGE,DOB) values("Muhammad Arsalan","mrbadshahbusiness@gmail.com","03172170569","17","20/02/2006");

update info set email = "arsalanakbarali53@gmail.com" where id ='7';

alter table info add ADDRESS varchar(225);
alter table info add EROLLCOUSE varchar(225);
alter table info add FEES varchar(225);


UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='1';
UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='2';
UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='3';
UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='4';
UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='5';
UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='6';
UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='7';
UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='8';
UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='9';
UPDATE INFO SET ADDRESS ="HOUSE NO B-262 AZAM NAGAR LIAQUATABAD" , EROLLCOUSE = "WEB DEVOLPMENT" , FEES ="FULL PAYMEMT OF CASH" WHERE ID='10'